### ISSUE TITLE
bazel-toolchains red on bazel ci

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel-toolchains#110]
Howdy,
bazel-toolchains are red on bazel ci: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#1a4a78fb-0b11-4d4d-a022-bbda5f628f44

@buchgr suspects it's because bazel 0.15.0 now uses jdk9. I'm not sure who's the proper owner of this issue so please delegate as needed.

Thanks!

**Comment by buchgr** [comment]
It's fine. We'll just wait for a 0.15.0 release of bazel toolchains. @erain is typically very fast :-)

**Comment by nlopezgi** [comment]
If you are referring to builds with remote execution service being red due to Bazel 0.15.0 now uses jdk9 the fix is to add the following flags to your remote builds: 
java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8

**Comment by mhlopko** [comment]
I'm sorry I messed up bazel-toolchains with bazel-remote-execution :) Please ignore this :)
