### ISSUE TITLE
Make snippets on the releases page buildifier-formatted

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel-toolchains#247]
Hello dear bazel-toolchains :)

I noticed today that the snippets you provide on https://releases.bazel.build/bazel-toolchains.html are not buildifier-formatted, so in order to update it I have to paste it into WORKSPACE, and then run buildifier on it. I know it's a nit, but could we get an already formatted snippet?

Thank you very much!

**Comment by nlopezgi** [comment]
done.

**Comment by mhlopko** [comment]
You rock! Thank you!
