### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-toolchains#272]
To make sure this repository continues working, we should make sure it's compatible with `--all_incompatible_changes`.

As a first step, I suggest trying with `--incompatible_no_transitive_loads` (as I plan to flip this flag soon).

Let me know if you need help (I didn't manage to test this repository without credentials).

**Comment by xingao267** [comment]
Fix in dependent repo: https://github.com/GoogleContainerTools/base-images-docker/pull/274

**Comment by xingao267** [comment]
Fix in dependent repo: https://github.com/bazelbuild/rules_docker/pull/648

**Comment by xingao267** [comment]
Fixed.
