### ISSUE TITLE
dangling symlink in jdk

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel-toolchains#445]
The JDK you are shipping has a dangling symlink `/usr/lib/jvm/java-8-openjdk-amd64/src.zip`. I need to delete them in the Bazel RBE docker image because we have some tests that inspect the JDK and fail if there is a dangling symlink. Seems like it shouldn't be there in the first place?

**Comment by xingao267** [comment]
It seems the broken link is installed by `apt-get` of `openjdk-8-jdk-headless` package. I'll send a PR to remove that link at the end of container generation.

**Comment by xingao267** [comment]
Code is merged in https://github.com/GoogleCloudPlatform/layer-definitions/pull/105. Doing a new container release now.

**Comment by xingao267** [comment]
The container is available at gcr.io/cloud-marketplace/google/rbe-ubuntu16-04@sha256:677c1317f14c6fd5eba2fd8ec645bfdc5119f64b3e5e944e13c89e0525cc8ad1 which has the dangling symlink removed.
