### ISSUE TITLE
Latest toolchain doesn't work with bazel 0.25.1

### ISSUE THREAD

**Issue by palvarez89** [bazelbuild/bazel-toolchains#497]
Latest release of bazel seems to not allow defining 'cpu' and 'compiler' in the toolchain. Because of this, when using this toolchain is giving me this error:

```
ERROR: /home/pedro/.cache/bazel/_bazel_pedro/eb366111355e69c7afe372aacd5d95ad/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.22.0/default/BUILD:85:1: in cc_toolchain rule @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.22.0/default:cc-compiler-armeabi-v7a: attributes 'cpu' and 'compiler' have been deprecated, please remove them. See https://github.com/bazelbuild/bazel/issues/7075 for details.
```

I haven't had much time to investigate if this error is correct, or not, but raising it now before I forget.

**Comment by nlopezgi** [comment]
Hi @palvarez89 ,
Thanks for opening this issue.
In that build you are using `//configs/ubuntu16_04_clang/1.1/bazel_0.22.0/default/BUILD`
Which works with **bazel_0.22.0**
You should switch to using a more recent config (e.g. https://github.com/bazelbuild/bazel-toolchains/tree/master/configs/ubuntu16_04_clang/1.2/bazel_0.25.0), or better yet, switch to using `rbe_autoconfig` (https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/rbe_repo.bzl#L15) to automatically pick the right config for your RBE builds depending on which version of Bazel you are using.

**Comment by nlopezgi** [comment]
(also dont forget to regularly update your pin to bazel-toolchains repo after each Bazel release)

**Comment by palvarez89** [comment]
@nlopezgi thanks for pointing that out. I totally missed I was hardcoding the toolchain version :)
