### ISSUE TITLE
Build breakage with upcoming Python toolchain change

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel-toolchains#501]
According to the Bazelisk pipeline, this project [fails](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/104#c46f5c33-c3f8-4e2f-84ef-7bad7b913108/6696-6776) when [`--incompatible_use_python_toolchains`](https://github.com/bazelbuild/bazel/issues/7899) is enabled. This flag was introduced in Bazel 0.25 and will be flipped in Bazel 0.27.

It looks like `rules_docker`'s `join_layers` script is being built in the host configuration, causing it to be built for PY3 rather than PY2 due to bazelbuild/bazel#6443. You may need to add `--host_force_python=PY2` to your build, or ask the upstream dependency to migrate the host tool to Python 3.

**Comment by nlopezgi** [comment]
thanks @brandjon,
I'm fixing a couple of issues preventing us from updating to latest rules_docker pin and will also add --host_force_python=PY2 to our bazelrc to be used in all our builds soon

**Comment by brandjon** [comment]
FYI this is still failing in a recent [presubmit of head + flag flip](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1008#e8b58f78-a439-40ab-8b1c-edac4afcf98b). I'll be flipping the flag imminently. The error message confirms this is related to `--host_force_python=PY2` (I think if you add it to your bazelrc our CI should pick it up, but if that's not working you can [file an issue](https://github.com/bazelbuild/continuous-integration/issues) with our engprod team.)

**Comment by nlopezgi** [comment]
thanks for the nudge, had forgotten about this but should be just a matter of adding the flag to our bazelrc.
