### ISSUE TITLE
[feature] ubuntu1804_clang toolchain

### ISSUE THREAD

**Issue by brycearden** [bazelbuild/bazel-toolchains#606]
The GCC version in ubuntu16-04 is old-ish (4.9.3) and breaks for me when compiling the antlr4 cpp runtime because they use the [codecvt header](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/antlr4-common.h#L11). This issue would be solved by updating the base image to something with gcc >= 5.0. Are there plans to release any toolchains for `ubuntu1804_clang` or `rbe-ubuntu18-04`? I'd like to avoid rolling my own toolchain definitions if possible, and the existing toolchains break for me when doing an `apt-get install gcc` inside the container. It is fixable by doing a `apt-get install libstdc++-5-dev` however.

**Comment by shahms** [comment]
FWIW the libstdc++ shipped with Ubuntu 16.04 is too old to support C++17 and there aren't any readily available backports of libstdc++-7 available.  An rbe_ubuntu1804 container would be very welcome.

**Comment by nlopezgi** [comment]
Thanks for creating this issue.
atm we have no plans to create an Ubuntu 18.04 toolchain, but we might be able to plan for this in Q4 2019. I'll sync up with other folks involved and provide a rough estimate soon.

In the meantime, you can create a toolchain based off gcr.io/gcp-runtimes/ubuntu_18_0_4. You'd need to install all tools yourself there and create your own toolchain configs.

**Comment by shahms** [comment]
Yes, that latter part is why we have not done so.  Creating and maintaining our own toolchains is prohibitively difficult given both the complexity of their definitions (particularly C++) and currently shifting landscape.

**Comment by nlopezgi** [comment]
Thanks for the clarification. I will post updates here once I have more info about estimates.

**Comment by nlopezgi** [comment]
RBE ubuntu 18.04 container is now public in  in http://gcr.io/cloud-marketplace/google/rbe-ubuntu18-04 and comes with c++17

example target in WORKSPACE to use new container with RBE:

```
load("@bazel_toolchains//rules:environments.bzl", "clang_env")
rbe_autoconfig(
    name = "rbe_ubuntu1804",
    env = clang_env(),
    registry = "gcr.io",
    repository = "cloud-marketplace/google/rbe-ubuntu18-04",
    digest = "sha256:0191ae7277b35b787851168d1900ec36d0a47744315638aa0a00d078ca1dc63c",
)
```

We will not be publishing toolchain configs for this container, so using this container will require pulling the container from your host environment, or you can follow advice in documentation for rbe_autoconfig (https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/rbe_repo.bzl#L53) to create the configs yourself and check them into a repo.

Note you can also use the non-auth endpoint for this container:

```
rbe_autoconfig(
    name = "rbe_ubuntu1804",
    env = clang_env(),
    registry = "l.gcr.io",
    repository = "google/rbe-ubuntu18-04",
    digest = "sha256:0191ae7277b35b787851168d1900ec36d0a47744315638aa0a00d078ca1dc63c",
)
```

**Comment by finn-ball** [comment]
What is the reason why an official Ubuntu18-04 toolchain isn't supported whilst the rbe image is?

**Comment by nlopezgi** [comment]
You can create and host configs for Ubuntu 18.04 if you need to with rbe_autoconfig. Configs hosted in this repo are provided as a convenience and not necessarily to provide support for any particular env.

**Comment by finn-ball** [comment]
I managed to create a toolchain with auto-config but now it pulls down the whole image in order to run it. Is there an easy way to grab the generated toolchain and wrap it for future use?

**Comment by nlopezgi** [comment]
Please see https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/rbe_repo.bzl#L53 and let me know if you have further questions.
