### ISSUE TITLE
Release compatible with 1.0.1

### ISSUE THREAD

**Issue by robbertvanginkel** [bazelbuild/bazel-toolchains#757]
#751 adds support for 1.0.1, but its commit (9b2a0f99064a57cd6e6ca073f8f8bee8189143b6, which in title says 1.0.0 support but the code is for 1.0.1) isn't in the 1.0.1 release tag https://github.com/bazelbuild/bazel-toolchains/releases/tag/1.0.1. Support for 1.0.1 is also not in in the 1.1.0 tag https://github.com/bazelbuild/bazel-toolchains/releases/tag/1.1.0.

Could we tag a released version which includes the commit with 1.0.1?

**Comment by robbertvanginkel** [comment]
cc @nlopezgi

**Comment by smukherj1** [comment]
Hi @robbertvanginkel,

Is using Bazel toolchains at `HEAD` an option?

```
http_archive(
        name = "bazel_toolchains",
        sha256 = "078b1861f63698a861ee28d5918be3852e832f632b378b816737895a0825ed70",
        strip_prefix = "bazel-toolchains-4c49795537110ebd41991cc055cd772cd192b00b",
        urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/4c49795537110ebd41991cc055cd772cd192b00b.tar.gz"],                                                                                                            
)
```

**Comment by robbertvanginkel** [comment]
Using `HEAD` would work, but I think it'd still make sense if there was a  released version to use.

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/bazel-toolchains/releases/tag/1.1.1 is out
