### ISSUE TITLE
Release compatible with Bazel 2.0.0

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel-toolchains#788]
Bazel 2.0.0 has recently been released. It would be very helpful if there was a matching release of bazel-toolchains :)

**Comment by nlopezgi** [comment]
Bazel release was 3h ago, automation should kick in soon to push a release for bazel-toolchains, thanks for creating this issue

**Comment by shs96c** [comment]
Hahaha! I apologise. I thought it had been a little longer than that :) Many thanks for your gracious comment!

**Comment by nlopezgi** [comment]
We might be a bit delayed with the release, apologies

**Comment by nlopezgi** [comment]
Configs are out
