### ISSUE TITLE
Checked in config needed for Bazel 1.2.1, 2.0.0

### ISSUE THREAD

**Issue by dv-brianmickel** [bazelbuild/bazel-toolchains#802]
# Warning Message

> bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_default not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map
{"0.20.0": ["8.0.0"],"0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"],
"1.0.0": ["9.0.0", "10.0.0"],
"1.0.1": ["10.0.0"],
"1.1.0": ["10.0.0"]}

# Relevant File
https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/rbe_repo/checked_in.bzl

**Comment by nlopezgi** [comment]
Please make sure you are pinned to the latest release of this repo as the latest version [does](https://github.com/bazelbuild/bazel-toolchains/blob/master/configs/ubuntu16_04_clang/versions.bzl) include the 1.2.1 and 2.0.0 configs.
