### ISSUE TITLE
SHA256 specified for release 2.1.0 seems to be wrong

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/bazel-toolchains#825]
While trying to upgrade to [release 2.1.0](https://github.com/bazelbuild/bazel-toolchains/releases/tag/2.1.0) I realized that the SHA256 specified in the release notes is incorrect.
The actual SHA256 of the tagged commit `2cd73fd57fc4b8e90e6f47e7254496279c747862` seems to be `7fb8cfb86fffed4574b255ffe3c188403b505f5e502367fc90b6290257ca9d17`.

Another minor issue is that the package is not available on the [mirror](https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/archive/2cd73fd57fc4b8e90e6f47e7254496279c747862.tar.gz).

**Comment by nlopezgi** [comment]
Thanks for opening this issue, I forgot to update the readme and publish the new package, will do so in a bit

**Comment by nlopezgi** [comment]
I just uploaded the new package and checked out that sha for `https://github.com/bazelbuild/bazel-toolchains/releases/download/2.1.0/bazel-toolchains-2.1.0.tar.gz` is indeed the published one `4d348abfaddbcee0c077fc51bb1177065c3663191588ab3d958f027cbfe1818b`. I also double checked that the mirror file is available in https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/archive/2.1.0.tar.gz . Closing but let me know if you run into other issues

**Comment by sha1n** [comment]
Sure - will let you know if there is a problem. 
Thanks for the quick response.

**Comment by sha1n** [comment]
Works - 10x
