### ISSUE TITLE
http_archive requires import

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel-toolchains#826]
This page:
```
https://releases.bazel.build/bazel-toolchains.html
```

is missing a line to import ```http_archive``` like so:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
```

**Comment by smukherj1** [comment]
Thanks for reporting. Our internal tool that generates the release notes has been updated to include the import statement. The release notes should get updated the next time we have a toolchain configs release (should happen within a week or two).

For reference, the latest toolchain configs release right now is [2.1.1](https://github.com/bazelbuild/bazel-toolchains/releases/tag/2.1.1).
