### ISSUE TITLE
Releases are not mirrored to GCS

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-toolchains#833]
https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/releases/download/2.1.1/bazel-toolchains-2.1.1.tar.gz is a 404

I've been mirroring releases myself but I'm leaving Google and losing access required to do that.
/cc @philwo

**Comment by smukherj1** [comment]
According to the release notes [here](https://releases.bazel.build/bazel-toolchains.html) the mirror is indeed created but at the `archive` link. However, the tool that generates toolchain configs and uploads the configs to the mirror has been updated to upload it automatically to the releases URL in the Bazel mirror going forward. The release notes will get updated to reflect this going forward.
