### ISSUE TITLE
Generating Windows toolchains for RBE

### ISSUE THREAD

**Issue by sunjayBhatia** [bazelbuild/bazel-toolchains#855]
We are trying to get RBE working for Envoy + Windows. It will be a huge help with our builds in CI and development.

We have hacked together changes to `bazel-toolchains` [here](https://github.com/greenhouse-org/bazel-toolchains/tree/enable-rbe-toolchain-generation-windows) (and have generated a toolchain for Envoy [here](https://github.com/greenhouse-org/envoy-build-tools/tree/generate-windows-msvc-toolchain) that we intend to test out) and are wondering if you would take the (cleaned up) changes so we can upstream toolchain generation for Windows.

I thought we would begin with this issue to gauge the maintainer's/community interest in supporting this upstream and we can continue and submit PRs as necessary.

*Links*
- Envoy tracking issue: https://github.com/envoyproxy/envoy/issues/10619
- `bazel-toolchains` fork: https://github.com/greenhouse-org/bazel-toolchains/tree/enable-rbe-toolchain-generation-windows
- `envoy-build-tools` fork: https://github.com/greenhouse-org/envoy-build-tools/tree/generate-windows-msvc-toolchain

**Comment by sunjayBhatia** [comment]
The gRPC and tensorflow projects are some other than Envoy that could benefit from this track of work as they build on Windows currently with RBE with what I gather is a manually generated toolchain

**Comment by smukherj1** [comment]
I hope to have an update on this by the end of this week. Apologies for the wait!

**Comment by sunjayBhatia** [comment]
@smukherj1 we haven't been able to get to it as yet, but were planning on submitting PRs soon, does that line up with your update or are the maintainers already working on Windows support?

**Comment by smukherj1** [comment]
Hi @sunjayBhatia,

Sorry for the delay in getting back. We aren't working on Windows support in this repo yet but I would be interested in seeing PRs that add windows support to the toolchain config generation rules.

I took a quick look at the commits in one of the bazel-toolchains forks you linked to and the changes seem reasonable (example [commit](https://github.com/greenhouse-org/bazel-toolchains/commit/dd9ab8a81a154ffde95095bac0caa23eaf040feb)), i.e., they shouldn't require a major refactor of the existing rules. Obviously that commit breaks Linux support and that will need to be cleaned up :)

My only concern is testing coverage. Since we don't plan to host windows configs, it won't be trivial to verify if the configs the modified rules generate will actually be accepted by Bazel in a remotely executed build on windows. I think the best starting point will be to extend our Bazel CI tests (config [here](https://github.com/bazelbuild/bazel-toolchains/blob/master/.bazelci/presubmit.yml) and instructions [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md)) to do some basic content checks on the generated configs.

**Comment by sunjayBhatia** [comment]
@smukherj1 Awesome! Thats great to hear. I think we expected that Windows configs wouldn't be hosted in this repo but that totally works for us if we can get the changes to the generation rules upstreamed. After our spike we have started looking into testing as you mention and are hoping to get that working as well. Thanks for the pointers to documentation 👍 

If we need additional pointers, is this issue the best place for a dialogue?

**Comment by smukherj1** [comment]
> If we need additional pointers, is this issue the best place for a dialogue?
sgtm

**Comment by sunjayBhatia** [comment]
Just informational, we do need https://github.com/bazelbuild/bazel/commit/ee6e1c256e8e5d1e356769b3b433c39ccd0c5e28 to get through to a bazel release to get our work pushed through, as the `local_config_cc/...` target is used and is currently not usable on Windows

**Comment by sunjayBhatia** [comment]
Draft PR we have going for our Windows work: https://github.com/bazelbuild/bazel-toolchains/pull/873

**Comment by smukherj1** [comment]
> Draft PR we have going for our Windows work: #873

Left a comment regarding structuring the code.

Unrelated question: I received some feedback originally from your team about lack of documentation about setting up Windows on RBE. While it's true that we currently don't have any publicly available documentation related to setting up for Windows, I wanted to know if expediting the creation of a new doc would be of any help to you.

We have an internal README that explains how to create a Windows worker pool, build a toolchain image, generate configs (not with rbe_autoconfig but with an old process that manually runs Bazel inside the container to generate the configs) and use those configs with Bazel to run a build remotely.

However, I feel you're already past the point of generating the image and creating configs. Any idea if sharing these instructions with you would be of any help at this point? If the only thing you need help with is what flags to pass to Bazel, I suggest looking at our reference bazelrc [here](https://github.com/bazelbuild/bazel-toolchains/blob/master/bazelrc/bazel-2.0.0.bazelrc) to configs Bazel on Linux for use with `rbe_autoconfig`. The only additional flags I see in our internal windows user guide are:
* Specifying the path to bash.exe in the toolchain image using [--shell_executable](https://docs.bazel.build/versions/master/command-line-reference.html#flag--shell_executable)

**Comment by sunjayBhatia** [comment]
Thanks very much for helping us with that, that summary of the existing Windows documentation is very helpful. Given the doc is more about the old process for Windows ("generate configs (not with rbe_autoconfig but with an old process that manually runs Bazel inside the container to generate the configs) and use those configs with Bazel to run a build remotely."), I think we're probably ok for now and don't need anything additional. Since trying to replicate the old process programmatically is less optimal than getting rbe_autoconfig to work, which we can do, we can forgo that ask of you.

Once we're able to get a Windows worker pool we might have to bother yall if things go wrong, but I think while we're working on that and getting our rbe_autoconfig changes upstreamed we should be good for now!

**Comment by sunjayBhatia** [comment]
Given our PR has been merged, we can close this out
