### ISSUE TITLE
Link error in rules_go upgrading bazel_toolchains from 2.2.0 to 3.0.1

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-toolchains#859]
I'm trying to upgrade the `bazel_toolchains` repository in the rules_go `WORKSPACE` file from 2.2.0 to 3.0.1. During that upgrade, I started seeing link errors in cgo tests.

The first one I saw was in [build 1926](https://buildkite.com/bazel/rules-go-golang/builds/1926#240dbbb2-318b-4636-a54b-4c7c22908be8). These .o files are compiled from generated .c files. One of them has `const int value = 2;`. The others have `const int value;`. I think that should link without error.

```
/usr/bin/ld.gold: error: /tmp/rules_go_work-630015290/_x2.o: multiple definition of 'value'
/usr/bin/ld.gold: /tmp/rules_go_work-630015290/_x1.o: previous definition here
/usr/bin/ld.gold: error: /tmp/rules_go_work-630015290/_x3.o: multiple definition of 'value'
/usr/bin/ld.gold: /tmp/rules_go_work-630015290/_x1.o: previous definition here
```

I enabled some verbose output in [build 1928](https://buildkite.com/bazel/rules-go-golang/builds/1928#3b5698d8-8afb-49ed-927c-556bc44051b3). It fails building a different test, but the error is similar.

Any idea what might have changed between 2.2.0 and 3.0.1 that could have caused this? I think that's the only variable here. Unfortunately, the generated C files are just temporary (not part of the action graph), so I don't think there's any way to retrieve them.

**Comment by smukherj1** [comment]
> The first one I saw was in build 1926. These .o files are compiled from generated .c files. One of them has const int value = 2;. The others have const int value;. I think that should link without error.

Is that accurate? I would think every declaration except one would need to have `extern`? Otherwise, you indeed have multiple definitions.

**Comment by jayconrod** [comment]
Maybe? `extern` wasn't necessary before.

What exactly changed between these versions? Is there a new compiler or linker?

**Comment by jayconrod** [comment]
Well, adding `extern` to constant declarations in all the tests made everything pass. Stricter linker I guess?

Seems to work in any case, so this can be closed.
